openapi: 3.0.0
info:
  title: Mock Healthcare System API
  version: 1.0.0
servers:
  - url: http://localhost:5001
paths:
  /patients:
    get:
      summary: Get all patients
      responses:
        '200':
          description: A list of patients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
  /appointments:
    get:
      summary: Get appointments
      responses:
        '200':
          description: A list of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
  /notify-pharmacy:
    post:
      summary: Notify pharmacy of appointment and perscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '200':
          description: Pharmacy notified successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotifyResponse'

components:
  schemas:
    Patient:
      type: object
      required: [id, name]
      properties:
        id: { type: string }
        name: { type: string }
    Appointment:
      type: object
      required: [id, patientId, date, medication, pharmacy]
      properties:
        id: { type: string }
        patientId: { type: string }
        date:
          type: string
          format: date-time
        medication: { type: string}
        pharmacy: { type: string }
    Notification:
      type: object
      required: [appointmentId, patientId, medication, pharmacy, message]
      properties:
        appointmentId: { type: string }
        patientId: { type: string}
        medication: { type: string}
        pharmacy: { type: string }
        message: { type: string }
    NotifyResponse:
      type: object
      properties:
        status: { type: string }
        appointmentId: { type: string }
        patientId: { type: string}
        medication: { type: string}
        pharmacy: { type: string }
        message: { type: string }
